django_blog/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    # path('', views.index, name="index"),
    path('', views.IndexView.as_view(), name="index"),
    path('post/<int:post_id>', views.details, name="details"),

]

django_blog/blogosphere/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('accounts/login', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

django_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    category_title = models.CharField(max_length=250)

    def __str__(self):
        return self.category_title

class Post(models.Model):
    post_title = models.CharField(max_length=250)
    body = models.TextField()
    draft = models.BooleanField(null=False, blank=True, default=True)
    pub_date = models.DateTimeField(verbose_name='Date published', null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.PROTECT, null=True)



    def __str__(self):
        return self.post_title

django_blog/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, DetailView

from .models import Category, Post

# def index(request):
#     title = 'Blogosphere'
#     posts = Post.objects.exclude(pub_date__gt=timezone.now()).order_by('-pub_date')
#     context = {
#         'title': title,
#         'posts': posts,
#     }
#     return render(request, "blog/index.html", context)

class IndexView( ListView):
    template_name = "blog/index.html"
    extra_context = {
        'title': 'Blogosphere',
    }
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.exclude(pub_date__gt=timezone.now()).order_by('-pub_date')


def details(request, post_id):
    # szczegóły wpisu dla zalgowantych
    post = Post.objects.get(id=post_id)
    title = post.post_title
    context = {
        'title': title,
        'post': post,
    }
    return render(request, "blog/details.html", context)


# Przeglądanie własnych wpisów (dla zalogowanych)
# Tworzenie własnych wpisów (dla zalogowanych)
# Edycja własnych wpisów (dla zalogowanych)

django_blog/blog/templates/accounts/login.html
{% extends "base.html" %}
{% block main %}

<div class="row">
    <h1 class="text-center">Login</h1>
</div>
<div class="row">
    <div class="col">
        {% if form.errors %}
        <p class="text-denger">Username and password are incorrect!</p>
        {% endif %}

        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}


            <div class="mb-3 row">
                <label for="id_username" class="col-sm-2 col-form-label">Username:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="id_username" name="username">
                </div>
            </div>
            <div class="mb-3 row">
                <label for="id_password" class="col-sm-2 col-form-label">Password:</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="id_password" name="password">
                </div>
            </div>

            <input type="hidden" name="next" value="{{ next }}">
            <input type="submit" class="btn btn-primary" value="Login">
        </form>
    </div>
</div>

{% endblock %}

django_blog/blog/templates/accounts/logout.html
{% extends "base.html" %}
{% block main %}

        <div class="row">
            <h1 class="text-center">Logged out</h1>
        </div>
        <div class="row">
            <div class="col">
                <p class="text-center">Have a nice day!</p>
            </div>
        </div>

{% endblock %}

django_blog/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>&bull; {{ title }} &bull;</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link href="{% static 'blog/main.css' %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blog:index' %}">Blogosphere</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
          </li>
      </ul>

      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Hello, {{ user.first_name }}</a>
              <ul class="dropdown-menu dropdown-menu-end">
                  {% if user.is_superuser %}
                  <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin panel</a></li>
                  {% endif %}
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
              </ul>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}

      </ul>


    </div>
  </div>
</nav>

    <main class="container">
        {% block main %}{% endblock %}
    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous">
    </script>
</body>
</html>

django_blog/blog/templates/blog/details.html
{% extends "base.html" %}
{% block main %}

<div class="row">
    <h1 class="text-center">{{ title }}</h1>
    <hr>
    <div class="text-center">{{ post.body }}</div>
    <p>Posted on: {{ post.pub_date }}, Author: {{ post.author }}, Category: {{ post.category }}</p>
</div>

{% endblock %}

django_blog/blog/templates/blog/index.html
{% extends "base.html" %}
{% block main %}

        {% for post in posts %}
        <div class="row">
            <section class="col">
                <h2 class="text-center"><a href="{% url 'blog:details' post.id %}">{{ post.post_title }}</h2></a>
                <div class="text-center">{{ post.body }}</div>
                <p>Posted on: {{ post.pub_date }}, Author: {{ post.author }}, Category: {{ post.category }}</p>
            </section>
        </div>
        {% endfor %}

 {% endblock %}